#ifndef __GTHREE_H__
#define __GTHREE_H__

#define __GTHREE_H_INSIDE__

#include <glib-object.h>
#include <gthree/gthreetypes.h>
#include <gthree/gthreetypebuiltins.h>
#include <gthree/gthreeenums.h>
#include <gthree/gthreeattribute.h>
#include <gthree/gthreemeshmaterial.h>
#include <gthree/gthreemeshbasicmaterial.h>
#include <gthree/gthreecamera.h>
#include <gthree/gthreeperspectivecamera.h>
#include <gthree/gthreeorthographiccamera.h>
#include <gthree/gthreegeometry.h>
#include <gthree/gthreelinebasicmaterial.h>
#include <gthree/gthreelinesegments.h>
#include <gthree/gthreematerial.h>
#include <gthree/gthreemesh.h>
#include <gthree/gthreeskinnedmesh.h>
#include <gthree/gthreeobject.h>
#include <gthree/gthreegroup.h>
#include <gthree/gthreerenderer.h>
#include <gthree/gthreescene.h>
#include <gthree/gthreetexture.h>
#include <gthree/gthreecubetexture.h>
#include <gthree/gthreeloader.h>
#include <gthree/gthreelight.h>
#include <gthree/gthreelightshadow.h>
#include <gthree/gthreeambientlight.h>
#include <gthree/gthreepointlight.h>
#include <gthree/gthreespotlight.h>
#include <gthree/gthreedirectionallight.h>
#include <gthree/gthreemeshlambertmaterial.h>
#include <gthree/gthreemeshphongmaterial.h>
#include <gthree/gthreemeshstandardmaterial.h>
#include <gthree/gthreemeshspecglosmaterial.h>
#include <gthree/gthreemeshnormalmaterial.h>
#include <gthree/gthreemeshdepthmaterial.h>
#include <gthree/gthreemeshdistancematerial.h>
#include <gthree/gthreeshadermaterial.h>
#include <gthree/gthreesprite.h>
#include <gthree/gthreespritematerial.h>
#include <gthree/gthreepoints.h>
#include <gthree/gthreepointsmaterial.h>
#include <gthree/gthreeprimitives.h>
#include <gthree/gthreebone.h>
#include <gthree/gthreelinearinterpolant.h>
#include <gthree/gthreediscreteinterpolant.h>
#include <gthree/gthreecubicinterpolant.h>
#include <gthree/gthreequaternioninterpolant.h>
#include <gthree/gthreekeyframetrack.h>
#include <gthree/gthreevectorkeyframetrack.h>
#include <gthree/gthreecolorkeyframetrack.h>
#include <gthree/gthreenumberkeyframetrack.h>
#include <gthree/gthreequaternionkeyframetrack.h>
#include <gthree/gthreeanimationclip.h>
#include <gthree/gthreeanimationmixer.h>
#include <gthree/gthreeanimationaction.h>
#include <gthree/gthreeeffectcomposer.h>
#include <gthree/gthreeraycaster.h>
#undef __GTHREE_H_INSIDE__

#endif /* __GTHREE_H__ */
